# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\"2\n\x0fRegisterRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"4\n\x10RegisterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"/\n\x0cLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\")\n\x07Session\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\"Q\n\rLoginResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x1e\n\x07session\x18\x03 \x01(\x0b\x32\r.auth.Session\"\'\n\x16ValidateSessionRequest\x12\r\n\x05token\x18\x01 \x01(\t\"9\n\x17ValidateSessionResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x0f\n\x07user_id\x18\x02 \x01(\t2\xca\x01\n\x0b\x41uthService\x12\x39\n\x08Register\x12\x15.auth.RegisterRequest\x1a\x16.auth.RegisterResponse\x12\x30\n\x05Login\x12\x12.auth.LoginRequest\x1a\x13.auth.LoginResponse\x12N\n\x0fValidateSession\x12\x1c.auth.ValidateSessionRequest\x1a\x1d.auth.ValidateSessionResponseBQ\n\x10\x63om.example.authZ=github.com/example/distributed-ticket-booking/proto/auth;authb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020com.example.authZ=github.com/example/distributed-ticket-booking/proto/auth;auth'
  _globals['_REGISTERREQUEST']._serialized_start=20
  _globals['_REGISTERREQUEST']._serialized_end=70
  _globals['_REGISTERRESPONSE']._serialized_start=72
  _globals['_REGISTERRESPONSE']._serialized_end=124
  _globals['_LOGINREQUEST']._serialized_start=126
  _globals['_LOGINREQUEST']._serialized_end=173
  _globals['_SESSION']._serialized_start=175
  _globals['_SESSION']._serialized_end=216
  _globals['_LOGINRESPONSE']._serialized_start=218
  _globals['_LOGINRESPONSE']._serialized_end=299
  _globals['_VALIDATESESSIONREQUEST']._serialized_start=301
  _globals['_VALIDATESESSIONREQUEST']._serialized_end=340
  _globals['_VALIDATESESSIONRESPONSE']._serialized_start=342
  _globals['_VALIDATESESSIONRESPONSE']._serialized_end=399
  _globals['_AUTHSERVICE']._serialized_start=402
  _globals['_AUTHSERVICE']._serialized_end=604
# @@protoc_insertion_point(module_scope)
