# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import booking_pb2 as booking__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in booking_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BookingServiceStub(object):
    """Booking service used by clients to query and book seats.
    The actual booking operation should be applied via the Raft state machine
    to ensure consistency across booking nodes.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddShow = channel.unary_unary(
                '/booking.BookingService/AddShow',
                request_serializer=booking__pb2.AddShowRequest.SerializeToString,
                response_deserializer=booking__pb2.AddShowResponse.FromString,
                _registered_method=True)
        self.BookSeat = channel.unary_unary(
                '/booking.BookingService/BookSeat',
                request_serializer=booking__pb2.BookRequest.SerializeToString,
                response_deserializer=booking__pb2.BookResponse.FromString,
                _registered_method=True)
        self.QuerySeat = channel.unary_unary(
                '/booking.BookingService/QuerySeat',
                request_serializer=booking__pb2.QueryRequest.SerializeToString,
                response_deserializer=booking__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.ListSeats = channel.unary_unary(
                '/booking.BookingService/ListSeats',
                request_serializer=booking__pb2.ListSeatsRequest.SerializeToString,
                response_deserializer=booking__pb2.ListSeatsResponse.FromString,
                _registered_method=True)


class BookingServiceServicer(object):
    """Booking service used by clients to query and book seats.
    The actual booking operation should be applied via the Raft state machine
    to ensure consistency across booking nodes.
    """

    def AddShow(self, request, context):
        """Admin RPC: Add a new show or update seat capacity/price for an existing show.
        <--- NEW RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BookSeat(self, request, context):
        """Book a specific seat for a user (goes through Payment -> Raft).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QuerySeat(self, request, context):
        """Query seat availability.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSeats(self, request, context):
        """List seat status for a show / event (paged).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddShow': grpc.unary_unary_rpc_method_handler(
                    servicer.AddShow,
                    request_deserializer=booking__pb2.AddShowRequest.FromString,
                    response_serializer=booking__pb2.AddShowResponse.SerializeToString,
            ),
            'BookSeat': grpc.unary_unary_rpc_method_handler(
                    servicer.BookSeat,
                    request_deserializer=booking__pb2.BookRequest.FromString,
                    response_serializer=booking__pb2.BookResponse.SerializeToString,
            ),
            'QuerySeat': grpc.unary_unary_rpc_method_handler(
                    servicer.QuerySeat,
                    request_deserializer=booking__pb2.QueryRequest.FromString,
                    response_serializer=booking__pb2.QueryResponse.SerializeToString,
            ),
            'ListSeats': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSeats,
                    request_deserializer=booking__pb2.ListSeatsRequest.FromString,
                    response_serializer=booking__pb2.ListSeatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'booking.BookingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('booking.BookingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BookingService(object):
    """Booking service used by clients to query and book seats.
    The actual booking operation should be applied via the Raft state machine
    to ensure consistency across booking nodes.
    """

    @staticmethod
    def AddShow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booking.BookingService/AddShow',
            booking__pb2.AddShowRequest.SerializeToString,
            booking__pb2.AddShowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BookSeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booking.BookingService/BookSeat',
            booking__pb2.BookRequest.SerializeToString,
            booking__pb2.BookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QuerySeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booking.BookingService/QuerySeat',
            booking__pb2.QueryRequest.SerializeToString,
            booking__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSeats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booking.BookingService/ListSeats',
            booking__pb2.ListSeatsRequest.SerializeToString,
            booking__pb2.ListSeatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
