# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: booking.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'booking.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbooking.proto\x12\x07\x62ooking\"o\n\x0b\x42ookRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07seat_id\x18\x02 \x01(\x05\x12\x0f\n\x07show_id\x18\x03 \x01(\t\x12\x16\n\x0e\x63orrelation_id\x18\x04 \x01(\t\x12\x15\n\rpayment_token\x18\x05 \x01(\t\"a\n\x0c\x42ookResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x12\n\nbooking_id\x18\x03 \x01(\x03\x12\x1b\n\x04seat\x18\x04 \x01(\x0b\x32\r.booking.Seat\"0\n\x0cQueryRequest\x12\x0f\n\x07show_id\x18\x01 \x01(\t\x12\x0f\n\x07seat_id\x18\x02 \x01(\x05\"?\n\rQueryResponse\x12\x11\n\tavailable\x18\x01 \x01(\x08\x12\x1b\n\x04seat\x18\x02 \x01(\x0b\x32\r.booking.Seat\"J\n\x10ListSeatsRequest\x12\x0f\n\x07show_id\x18\x01 \x01(\t\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\x05\"J\n\x11ListSeatsResponse\x12\x1c\n\x05seats\x18\x01 \x03(\x0b\x32\r.booking.Seat\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\x05\"x\n\x04Seat\x12\x0f\n\x07seat_id\x18\x01 \x01(\x05\x12\x0f\n\x07show_id\x18\x02 \x01(\t\x12\x10\n\x08reserved\x18\x03 \x01(\x08\x12\x13\n\x0breserved_by\x18\x04 \x01(\t\x12\x13\n\x0breserved_at\x18\x05 \x01(\x03\x12\x12\n\nbooking_id\x18\x06 \x01(\x03\x32\xc9\x01\n\x0e\x42ookingService\x12\x37\n\x08\x42ookSeat\x12\x14.booking.BookRequest\x1a\x15.booking.BookResponse\x12:\n\tQuerySeat\x12\x15.booking.QueryRequest\x1a\x16.booking.QueryResponse\x12\x42\n\tListSeats\x12\x19.booking.ListSeatsRequest\x1a\x1a.booking.ListSeatsResponseBZ\n\x13\x63om.example.bookingZCgithub.com/example/distributed-ticket-booking/proto/booking;bookingb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'booking_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023com.example.bookingZCgithub.com/example/distributed-ticket-booking/proto/booking;booking'
  _globals['_BOOKREQUEST']._serialized_start=26
  _globals['_BOOKREQUEST']._serialized_end=137
  _globals['_BOOKRESPONSE']._serialized_start=139
  _globals['_BOOKRESPONSE']._serialized_end=236
  _globals['_QUERYREQUEST']._serialized_start=238
  _globals['_QUERYREQUEST']._serialized_end=286
  _globals['_QUERYRESPONSE']._serialized_start=288
  _globals['_QUERYRESPONSE']._serialized_end=351
  _globals['_LISTSEATSREQUEST']._serialized_start=353
  _globals['_LISTSEATSREQUEST']._serialized_end=427
  _globals['_LISTSEATSRESPONSE']._serialized_start=429
  _globals['_LISTSEATSRESPONSE']._serialized_end=503
  _globals['_SEAT']._serialized_start=505
  _globals['_SEAT']._serialized_end=625
  _globals['_BOOKINGSERVICE']._serialized_start=628
  _globals['_BOOKINGSERVICE']._serialized_end=829
# @@protoc_insertion_point(module_scope)
