# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import chatbot_pb2 as chatbot__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in chatbot_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChatbotStub(object):
    """Simple chatbot used to help users pick seats, answer booking questions, etc.
    This is intentionally lightweight — you can later add streaming or bi-directional RPCs.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ask = channel.unary_unary(
                '/chatbot.Chatbot/Ask',
                request_serializer=chatbot__pb2.AskRequest.SerializeToString,
                response_deserializer=chatbot__pb2.AskResponse.FromString,
                _registered_method=True)


class ChatbotServicer(object):
    """Simple chatbot used to help users pick seats, answer booking questions, etc.
    This is intentionally lightweight — you can later add streaming or bi-directional RPCs.

    """

    def Ask(self, request, context):
        """Simple single-turn chat.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatbotServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ask': grpc.unary_unary_rpc_method_handler(
                    servicer.Ask,
                    request_deserializer=chatbot__pb2.AskRequest.FromString,
                    response_serializer=chatbot__pb2.AskResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chatbot.Chatbot', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chatbot.Chatbot', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Chatbot(object):
    """Simple chatbot used to help users pick seats, answer booking questions, etc.
    This is intentionally lightweight — you can later add streaming or bi-directional RPCs.

    """

    @staticmethod
    def Ask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chatbot.Chatbot/Ask',
            chatbot__pb2.AskRequest.SerializeToString,
            chatbot__pb2.AskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
