# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chatbot.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'chatbot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rchatbot.proto\x12\x07\x63hatbot\"\xa2\x01\n\nAskRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x12\n\nsession_id\x18\x03 \x01(\t\x12\x31\n\x07\x63ontext\x18\x04 \x03(\x0b\x32 .chatbot.AskRequest.ContextEntry\x1a.\n\x0c\x43ontextEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"[\n\x0b\x41skResponse\x12\x12\n\nreply_text\x18\x01 \x01(\t\x12\x0e\n\x06intent\x18\x02 \x01(\t\x12(\n\x0bsuggestions\x18\x03 \x03(\x0b\x32\x13.chatbot.Suggestion\",\n\nSuggestion\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\t2;\n\x07\x43hatbot\x12\x30\n\x03\x41sk\x12\x13.chatbot.AskRequest\x1a\x14.chatbot.AskResponseBZ\n\x13\x63om.example.chatbotZCgithub.com/example/distributed-ticket-booking/proto/chatbot;chatbotb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chatbot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023com.example.chatbotZCgithub.com/example/distributed-ticket-booking/proto/chatbot;chatbot'
  _globals['_ASKREQUEST_CONTEXTENTRY']._loaded_options = None
  _globals['_ASKREQUEST_CONTEXTENTRY']._serialized_options = b'8\001'
  _globals['_ASKREQUEST']._serialized_start=27
  _globals['_ASKREQUEST']._serialized_end=189
  _globals['_ASKREQUEST_CONTEXTENTRY']._serialized_start=143
  _globals['_ASKREQUEST_CONTEXTENTRY']._serialized_end=189
  _globals['_ASKRESPONSE']._serialized_start=191
  _globals['_ASKRESPONSE']._serialized_end=282
  _globals['_SUGGESTION']._serialized_start=284
  _globals['_SUGGESTION']._serialized_end=328
  _globals['_CHATBOT']._serialized_start=330
  _globals['_CHATBOT']._serialized_end=389
# @@protoc_insertion_point(module_scope)
